export const Products = [
  {
    id: "1",
    category: "officeChair",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "1",
    category: "bookshelf",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "2",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "3",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "4",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "5",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "6",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "7",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "8",
    category: "New Arrivals",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "9",
    category: "Best Sellers",
    image: "/Images/vass.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "10",
    category: "Best Sellers",
    image: "/Images/chairs2.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "11",
    category: "Sale Items",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "12",
    category: "Best Sellers",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "13",
    category: "Sale Items",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "14",
    category: "On Sales",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    dis: "-10%",
    desrate: "48.50",
    // like: <FavoriteBorderimage fontSize="13px" />,
  },
  {
    id: "15",
    category: "On Sales",
    image: "/Images/chairs.png",
    tag: "New",
    name: "Wooden decorations",
    quantity: 1,
    price: 38.5,
    // like: <FavoriteBorderimage fontSize="13px" />,
  },

  {
    id: 1,
    image: "/Images/shop1.png",
    name: "Afkgyfcghewfciis debitis",
    category: "Uncategorized",
    color: "red",
    price: 235,
    quantity: 1,
    rating: 2,
  },
  {
    id: 2,
    image: "/Images/shop2.png",
    name: "AKHGcs debitis",
    category: "Uncategorized",
    color: "red",
    price: 345,
    quantity: 1,
    rating: 3,
  },
  {
    id: 3,
    image: "/Images/shop3.png",
    name: "Officiis debitis",
    category: "Uncategorized",
    color: "blue",
    price: 65,
    quantity: 1,
    rating: 5,
  },
  {
    id: 4,
    image: "/Images/shop4.png",
    name: "mejhvficiis debitis",
    category: "Uncategorized",
    color: "blue",
    price: 115,
    quantity: 1,
    rating: 4,
  },
  {
    id: 5,
    image: "/Images/shop5.png",
    name: "Dfficiis debitis",
    category: "Uncategorized",
    color: "green",
    price: 455,
    quantity: 1,
    rating: 2,
  },
  {
    id: 6,
    image: "/Images/shop6.png",
    name: "Lfficiis debitis",
    category: "Diningroom",
    color: "green",
    price: 305,
    quantity: 1,
    rating: 4,
  },
  {
    id: 7,
    image: "/Images/shop7.png",
    name: "zfficiis debitis",
    category: "Bedroom",
    color: "yellow",
    price: 225,
    quantity: 1,
    rating: 3,
  },
  {
    id: 8,
    image: "/Images/shop8.png",
    name: "PPfficiis debitis",
    category: "Cook",
    color: "yellow",
    price: 45,
    quantity: 1,
    rating: 5,
  },
  {
    id: 9,
    image: "/Images/shop1.png",
    name: "Afkgyfcghewfciis debitis",
    category: "Uncategorized",
    color: "red",
    price: 235,
    quantity: 1,
    rating: 2,
  },
  {
    id: 10,
    image: "/Images/shop2.png",
    name: "AKHGcs debitis",
    category: "Uncategorized",
    color: "red",
    price: 345,
    quantity: 1,
    rating: 3,
  },
  {
    id: 11,
    image: "/Images/shop3.png",
    name: "Officiis debitis",
    category: "Uncategorized",
    color: "blue",
    price: 65,
    quantity: 1,
    rating: 5,
  },
  {
    id: 12,
    image: "/Images/shop4.png",
    name: "mejhvficiis debitis",
    category: "Uncategorized",
    color: "blue",
    price: 115,
    quantity: 1,
    rating: 4,
  },
  {
    id: 13,
    image: "/Images/shop5.png",
    name: "Dfficiis debitis",
    category: "Uncategorized",
    color: "green",
    price: 455,
    quantity: 1,
    rating: 2,
  },
  {
    id: 14,
    image: "/Images/shop6.png",
    name: "Lfficiis debitis",
    category: "light&sofa",
    color: "green",
    price: 305,
    quantity: 1,
    rating: 4,
  },
  {
    id: 14,
    image: "/Images/shop6.png",
    name: "Lfficiis debitis",
    category: "Diningroom",
    color: "green",
    price: 305,
    quantity: 1,
    rating: 4,
  },
  {
    id: 15,
    image: "/Images/shop7.png",
    name: "zfficiis debitis",
    category: "Bedroom",
    color: "yellow",
    price: 225,
    quantity: 1,
    rating: 3,
  },
  {
    id: 15,
    image: "/Images/shop7.png",
    name: "zfficiis debitis",
    category: "cornerTable",
    color: "yellow",
    price: 225,
    quantity: 1,
    rating: 3,
  },
  {
    id: 16,
    image: "/Images/shop8.png",
    category: "Cook",
    color: "yellow",
    price: 45,
    quantity: 1,
    tag: "New",
    name: "Wooden decorations",
    dis: "-10%",
    rating: 5,
  },
  {
    id: 16,
    image: "/Images/shop8.png",
    category: "ReadingTable",
    color: "yellow",
    price: 45,
    quantity: 1,
    tag: "New",
    name: "Wooden decorations",
    dis: "-10%",
    rating: 5,
  },
];
